//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ogretmenler
    {
        public int OgrtID { get; set; }
        public string OgrtAd { get; set; }
        public string OgrtSoyad { get; set; }
        public string OgrtTC { get; set; }
        public string OgrtTel { get; set; }
        public string OgrtMail { get; set; }
        public string OgrtSehir { get; set; }
        public string OgrtIlce { get; set; }
        public string OgrtAdres { get; set; }
        public string OgrtBrans { get; set; }
        public string OgrtFoto { get; set; }
    
        public virtual Tbl_Ayarlar Tbl_Ayarlar { get; set; }
    }
}
