//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ogrenciler
    {
        public short OgrncID { get; set; }
        public string OgrncAd { get; set; }
        public string OgrncSoyad { get; set; }
        public string OgrncNo { get; set; }
        public string OgrncSinif { get; set; }
        public string OgrncDogumTarihi { get; set; }
        public string OgrncCinsiyet { get; set; }
        public Nullable<int> OgrncVeliID { get; set; }
        public string OgrncTC { get; set; }
        public string OgrncSehir { get; set; }
        public string OgrncIlce { get; set; }
        public string OgrncAdres { get; set; }
        public string OgrncFoto { get; set; }
    
        public virtual Tbl_Veliler Tbl_Veliler { get; set; }
    }
}
